/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mamet' at '17/08/28 21:53' with Gradle 2.14.1
 *
 * @author mamet, @date 17/08/28 21:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
